image: node:lts

before_script:
  - yarn install

pages:
  script:
    - yarn build && yarn export
    - mv out public  # Move the static export output to public for GitLab Pages
  artifacts:
    paths:
      - public  # GitLab Pages serves from public/
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
