image: node:lts

before_script:
  - yarn

pages:
  script:
    - yarn build  # Build the standalone app
    - mkdir -p public
    - cp -r build/standalone public/  # Move standalone build to public
    - cp -r build/static public/build/static  # Ensure static files are included
  artifacts:
    paths:
      - public  # Expose the standalone build for GitLab Pages
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH