# The Docker image that will be used to build your app
image: node:lts
before_script:
  # Functions that should be executed before the build script is run
  - yarn install
pages:
  script:
    # Specify the steps involved to build your app here
    - yarn build
  artifacts:
    paths:
      # Store the "out" folder as an artifact so Pages can serve it
      - out
  # Publish the contents of the "out" folder to the web using Pages
  publish: out