import type { Metadata } from 'next'
import { Onest } from 'next/font/google'

import '@/styles/global.scss'
import '@/styles/helper.scss'
import '@mantine/core/styles.css'
import '@mantine/dates/styles.css'
import '@mantine/notifications/styles.css'

const geistSans = Onest({
  variable: '--font-onest-sans',
  subsets: ['latin'],
})

const geistMono = Onest({
  variable: '--font-onest-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export async function generateStaticParams() {
  return [{ locale: 'ro' }, { locale: 'ru' }]
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ro'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  )
}
